# Generated by Django 3.1.1 on 2021-03-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BOOK TITLE', max_length=200)),
                ('author', models.CharField(default='AUTHOR', max_length=200)),
                ('price', models.IntegerField()),
                ('publlisher', models.CharField(max_length=200)),
                ('edition', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
