# Generated by Django 3.1.1 on 2021-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
