# Generated by Django 3.1.1 on 2021-03-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.DateField(max_length=200),
        ),
    ]
