# Generated by Django 3.1.1 on 2021-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0003_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='publlisher',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='product/images'),
        ),
    ]
