# Generated by Django 3.1.1 on 2021-03-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0004_auto_20210330_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
