# Generated by Django 3.1.1 on 2021-03-29 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=20)),
                ('full_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('district', models.CharField(default=None, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField(default=None)),
                ('street_address', models.CharField(default=None, max_length=200)),
                ('house_no', models.CharField(default=None, max_length=200)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
