# Generated by Django 3.1.1 on 2021-03-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20210329_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
