# Generated by Django 3.1.1 on 2021-03-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20210319_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
