# Generated by Django 3.1.1 on 2021-03-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_auto_20210320_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
