# Generated by Django 3.1.1 on 2021-03-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=20)),
                ('full_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('pro_pic', models.ImageField(blank=True, null=True, upload_to='users/pro_pics')),
                ('address', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.address')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
